export const reviews = [
  {
    id: 1,
    name: "Iana Ibrahim",
    text: "Alles, was ich sagen kann, ist, dass Ayhan Kublay ein wirklich schönes und ordentliches Wimpernlifting macht. Es ist klar, dass die Künstlerin weiß, was sie tut, und auch ihre Beiträge auf Instagram zeigen sie als eine professionelle Expertin auf diesem Gebiet.",
    stars: 5,
  },
  {
    id: 2,
    name: "K.G.",
    text: "Einfach nur WOW! Ayhan hat mich sooooo freundlich und herzlich empfangen. Sie ist so ein herzlicher Mensch und sie berät einen einfach so toll. Ihre Arbeit ist einfach perfekt ! Leider gibt es nur 5 Sterne zu vergeben. Sie hat definitiv mehr verdient. Ich werde jetzt regelmäßig kommen und freue mich schon auf den nächsten Termin ♡",
    stars: 5,
  },
  {
    id: 3,
    name: "Mariam Hammoud",
    text: "bester Service aller Zeiten. Die Frau ist sehr freundlich und die Materialien sind so professionell. Sie hat die Arbeit korrigiert, die ich bei einer anderen Frau gemacht habe. Es war so professionell und detailbewusst. Die Ergebnisse sind perfekt, viel mehr als meine Erwartungen, und die Farbe ist so schön, echtes Braun. Die gesamte Linie meiner Wimpern wurde gezeichnet und mit einem Tattoo markiert, sodass meine Wimpern jetzt voller und dicker aussehen.",
    stars: 5,
  },
  {
    id: 4,
    name: "Maria Ziegler",
    text: "Ayhan arbeitet sehr präzise. Ihr ist es sehr wichtig, dass man mit dem Ergebnis zufrieden ist. Sie ist herzlich, ehrlich und hat sehr viel Geduld. Auf Wünsche werden eingegangen und die Beratung ist top! Ich kann Ayhan zu 110 % weiterempfehlen und bin mega zufrieden mit meinen Augenbrauen! Danke, danke, danke für diese tolle Arbeit!.",
    stars: 5,
  },
  {
    id:5,
    name: "YK",
    text: "Ich habe bei der lieben Ayhan eine Wimpernkranzverdichtung vornehmen lassen und bin mit dem Ergebnis sehr zufrieden. 🥰 Die Behandlung war schmerzfrei und das Ergebnis ist sehr schön. Ich werde oft darauf angesprochen und bin sehr glücklich damit.😊Ayhan war sehr zuvorkommend und hat sich viel Zeit für mich genommen. Wir haben spontan entschieden, meine Augenbrauen nachzustechen und sie hat das auch gleich gemacht.Ich bin sehr dankbar für die Empfehlung meiner Schwester und kann Ayhan nur weiterempfehlen.👍.",
    stars: 5,
  },
  {
    id: 6,
    name: "Meike Greiter",
    text: "Ayhan ist sehr freundlich und sehr erfahren. Man fühlt sich gut aufgehoben und ihre Arbeit ist einfach perfekt. Ich bin sehr zufrieden !.",
    stars: 5,
  },
  {
    id: 7,
    name: "Marion Karsch",
    text: "Von meiner Kosmetikerin haben mehrere Kunden die Ayhan empfohlen, weil sie sehr zufrieden waren. Ich hatte mir in der Türkei Oktober 2023 die Augenbrauen machen lassen und wegen notwendiger Nacharbeit suchte ich jemand in unserer Nähe. Vor dem ersten persönlichen Kontakt, habe ich Ayhan Bilder von meinen Augenbrauen gesendet. Da Ihr meine Augenbrauen nicht gefielen, wie mir selber auch nicht. Daraufhin hat sie mir einen persönlichen Beratungstermin angeboten. Mein Mann und ich sind gemeinsam zu ihr gefahren und waren sehr gut empfangen worden und eine Top Beratung erhalten. Zu diesem Zeitpunkt wollte sie mich nicht behandeln, weil es wirtschaftlich nichts gebracht hätte. Es soll die Zeit bis Herbst vergehen damit sie dann eine gute Arbeit ausführen kann. Von der ehrlichen Meinung von Ayhan waren wir sehr angenehm und positive überrascht. Nach einer Stunde sehr guten kostenloser Beratung, hat sie mir noch ein kleines Präsent und einen Pflegstift wegen Sonne für die Augenbrauen geschenkt.Ich freue mich schon auf den Herbsttermin bei Ayhan.",
    stars: 5,
  },
  {
    id: 8,
    name: "Sinem Kiran",
    text: "Absolut empfehlenswert! Bin immer wieder gerne bei ihr, sie macht sehr schöne Wimpernlifting 😍 Meine Wimpern halten bei ihr wirklich sehr sehr lang. Ich werde auch öfter darauf angesprochen, wo ich denn meine Wimpern machen lasse.Vielen Dank dafür! 🫶🏽.",
    stars: 5,
  },
  {
    id: 9,
    name: "Sabina Da Ma",
    text: "Ayhan ist eine super liebe. Sie ist sehr freundlich und nimmt sich Zeit für eine sehr gute Beratung und geht auf Kundenwünsche ein. Sehr zu empfehlen. Man fühlt sich direkt wohl bei ihr und in guten Händen. Weiter so!",
    stars: 5,
  },
  {
    id: 10,
    name: "Marins Müller",
    text: "Rundum perfekt 🥰Ayhan ist super lieb, nimmt sich Zeit, beratet toll und ehrlich und macht super Arbeit.Ich habe mich direkt wohl gefühlt und bin happy mit dem Ergebnis. Freue mich weitere Behandlung bei Ayhan machen zu lassen ☺️.",
    stars: 5,
  },
  {
    id: 11,
    name: "Ute Stein",
    text: "Ayhan hat mich sehr herzlich empfangen und mir die Behandlung eingehend erklärt. Nachdem sie mir einen Lidstrich tättowiert hat, werde ich auch für meine Augenbrauen zu ihr gehen. Ich freu mich schon.",
    stars: 5,
  },
  {
    id: 12,
    name: "B Fisher",
    text: "Ich habe mir eine Wimpernkranzverdichtung bei ihr stechen lassen, sieht total super aus und hat durch die Betäubungscreme nichtmal weh getan, nur ein bisschen gepiekst.Ayhan ist auch super lieb, hab mich gleich wohl gefühlt bei ihr! Die Terminvereinbarung erfolgt ganz unkompliziert über WhatsApp und wenn man Fragen hat oder irgendwas ist kann man sich jederzeit bei ihr melden.Kann sie nur empfehlen!Edit: Gehe immer wieder gerne zu ihr, habe mir jetzt noch ein Lippen PMU stechen lassen und das Ergebnis ist wirklich mega! 😍.",
    stars: 5,
  },
  {
    id:13 ,
    name: "Tina",
    text: "Ich habe mir von Ayhan Powderbrows stechen lassen, inkl. Korrektur der alten Arbeit aus einem großen Studio in Augsburg. Das Nachstechen steht noch aus, aber das Ergebnis ist schon jetzt sehr gut. Ich habe mich sehr gut aufgehoben gefühlt und wurde top beraten!",
    stars: 5,
  },
  {
    id:14 ,
    name: "Benjamin Gharbi",
    text: "Wer ein perfektes Permanent Ergebnis haben möchte, ist bei Ayhan genau richtig! Ich habe meinen Lidstrich und meine Augenbrauen auffrischen lassen.Und bin super begeistert!Saubere und gute Arbeit ist immer ihr Ziel! Ayhan ist sehr sympathisch und geht auf alle Wünsche ein. Ich bin sehr zufrieden und kann Sie nur jedem weiterempfehlen!",
    stars: 5,
  },
  {
    id:15 ,
    name: "Andrea Patzsch",
    text: "Ayhan ist eine sehr liebe Person und ich habe mich bei Ihr sehr wohl gefühlt. Sie hat meine Augenbrauen toll nach bearbeitet, nachdem ich in Augsburg bei jemand anderem schlechte Erfahrungen gemacht habe.",
    stars: 5,
  },
  {
    id:16 ,
    name: "Elmas Ozcelik",
    text: "Ayhan ist eine sehr liebe und ehlrliche Person. Ich wollte meine Lidstrich bei ihr machen lassen Sie hat mich so gut aufgklärt ich wusste sofort das ich in guten Händen bin einfach TOP...",
    stars: 5,
  },
  {
    id:17 ,
    name: "Jana Köln",
    text: "Ayhan ist ein so herzlicher Mensch und hat eine ganz liebevolle und lustige Art bei der man sich direkt wohlfühlt. Ihre Arbeit macht sie sehr sauber und einfach wunderschön. Bin sehr zufrieden bei ihr und werde definitiv wieder kommen",
    stars: 5,
  },
  {
    id:18 ,
    name: "Gülten Aytogmus",
    text: "Kompetente Beratung und super effektive Behandlung mit einem sofort sichtbaren Effekt! Sie nimmt sich sehr viel Zeit und gibt immer wertvolle Tipps mit. Ich freue mich auf jeden Termin bei ihr und kann das Studio herzlichst weiterempfehlen.Top",
    stars: 5,
  },
  {
    id:19 ,
    name: "Delina Patzsch",
    text: "Ayhan konnte meine Augenbrauen, welche von einem anderen Studio schlecht gemacht wurden, super korrigieren!!! Es sieht sehr viel besser aus als vorher.Zudem habe ich eine Top Beratung bekommen! Ich bin super zufrieden!",
    stars: 5,
  },
  {
    id:20 ,
    name: "Bettina P.",
    text: "Ich hatte heute meinen zweiten Termin für Powder Brows. Ich bin total happy, Ayhan als Beautyperle gefunden zu haben. Super sympathisch und ein tolles Ergebnis! Meine verzupften Naturbrauen, auch mit einer Vernarbung, waren bestimmt nicht der leichteste Fall. Ayhan arbeitet sehr korrekt und erklärt einem alles ganz toll! Die Betreuung während der Abheilphase war einzigartig.",
    stars: 5,
  },
  {
    id:21 ,
    name: "Jana Köhn",
    text: "Ayhan ist ein so herzlicher Mensch und hat eine ganz liebevolle und lustige Art bei der man sich direkt wohlfühlt. Ihre Arbeit macht sie sehr sauber und einfach wunderschön. Bin sehr zufrieden bei ihr und werde definitiv wieder kommen.",
    stars: 5,
  },
  {
    id:22 ,
    name: "Cika Kara",
    text: "Ich habe mir lidstrich stechen lassen. Ayhan hat super Arbeit geleistet :)Sehr nette Person mit derMan sogar reden und lachen kann. Geht auf Wünsche ein und beratet einen sehr gut bin sehr zufrieden und kann sie jedem weiterempfehlen nur :).",
    stars: 5,
  },
  {
    id:23 ,
    name: "Angelina Peter",
    text: "Ich habe bei Ayhan meine Augenbrauen und die Lippen stechen lassen und bin sehr sehr happy mit dem Ergebnis. Tolle Beratung, perfektionistisch angezeichnet und gestochen, gerechtfertigter Preis und ein supertoller Mensch!Dankeschön Ayhan",
    stars: 5,
  },
  {
    id:24 ,
    name: "Angelina Schneider",
    text: "Ich habe mich unglaublich wohl gefühlt und das ist bei mir sehr selten der Fall. Ayhan hat eine super Ausstrahlung und geht sehr vorsichtig und bedacht mit ihren Kunden um. Danke dir für diese tolle Zeit mit dir & die Behandlung - ich habe mich dank dir auch wieder wunderschön gefühlt",
    stars: 5,
  },
  {
    id: 25,
    name: "Tanja Müller",
    text: "Bei mir wurden die Augenbrauen gemacht. Ich bin mit dem Ergebnis sehr zufrieden. Ayhan leistet ausgezeichnete Arbeit. Sehr zu empfehlen. Kundenzufriedenheit steht hier definitiv an erster Stelle",
    stars: 5,
  },
  {
    id: 26,
    name: "Celina Patzsch",
    text: "Ayhan konnte meine Augenbrauen, welche von einem anderen Studio schlecht gemacht wurden, super korrigieren!!! Es sieht sehr viel besser aus als vorher.Zudem habe ich eine Top Beratung bekommen! Ich bin super zufrieden!",
    stars: 5,
  },
  {
    id: 27,
    name: "Sabrina Hampp",
    text: "Ayhan ist super nett und sympathisch. Ich hab mich bei ihr sofort wohl gefühlt und bin total glücklich mit dem Ergebnis. Kann sie nur weiterempfehlen",
    stars: 5,
  },
  {
    id: 28,
    name: "Natalia Fischer",
    text: "Auch von mir vielen Dank an Ayhan. Ich habe mich aufgehoben und wohl bei der Behandlung gefühlt. Da ich alte Pigmentierung hatte (grau, blau), nach Ayhans Behandlung habe ich sie nicht mehr. Ich bedanke mich noch mal sehr.",
    stars: 5,
  },
  {
    id: 29,
    name: "Selina Hofmann",
    text: "Ayhan hat aus meinen dünnen und sehr gerade wachsenden Wimpern wirklich das Beste rausgeholt beim Lashlifting! :)",
    stars: 5,
  },
  {
    id: 30,
    name: "B81",
    text: "Super professionell, ist auf meine Wünsche eingegangen und hat mich ausführlich beraten.Mein Lippen PMU ist bereits nach der ersten Behandlung schon richtig schön geworden.Die nächsten Termine für Augenbrauen und Wimpernkranzverdichtung stehen schon 🤍",
    stars: 5,
  },
  {
    id: 31,
    name: "oğuz Tep",    
    text: "Ayhan ist super nett, sehr kompetent man fühlt sich sehr wohl und gut aufgehoben bei Ihr. 🙏😊",
    stars: 5,
  },
  {
    id:32 ,
    name: "Nadine Böhner",
    text: "Wooow!!!Super schöne Augenbrauen! Bin sehr zufrieden Sehr sauber gearbeitet ♥️ Dankeschön 😇 ❤️❤️",
    stars: 5,
  },
  {
    id: 33,
    name: "Marina Vogel",
    text: "War zum Augenbrauen und Wimpernlifting da, bin sehr zufrieden.Ayhan ist unglaublich lieb und zuvorkommend! Man fühlt sich direkt wohl. Kann man nur empfehlen!❤️",
    stars: 5,
  },
  {
    id: 34,
    name: "Dany 90",
    text: "Ayhan ist super nett, man kann sich bei ihr nur wohlfühlen. Sie ist sehr kompetent und weiß was sie tut. Die Beratung und ihre Behandlung ist sehr professionell. Ich kann sie nur jedem weiterempfehlen ❤️",
    stars: 5,
  },
  {
    id:35 ,
    name: "EK",
    text: "Ich habe mir die Augenbrauen mit Microblading machen lassen. Die Form und die Farbe sind hervorragend geworden auch wie gewünscht sehr natürlich.Supernette Dame, auf meine Wünsche wurde eingegangen.",
    stars: 5,
  },
  {
    id:36 ,
    name: "Nadja",
    text: "Ayhan leistet tolle Arbeit. Sie geht auf die Kundenwünsche ein und zaubert einem ein zufriedenes Lächeln ins Gesicht. Ich fühle mich wie ein neuer Mensch, nachdem sie meinem Gesicht wieder Ausdruck verliehen hat! Sehr empfehlenswert!",
    stars: 5,
  },
  {
    id:37,
    name: "Raziye Yemisen",
    text: "Ich wurde sehr freundlich empfangen, Ayhan Kublay hat mich beim Wimpernlifting immer aufgeklärt, was sie macht. Sehr sauber und steril gearbeitet. Zum Schluß gab es auch ein Kundengeschenk. Bin sehr zufrieden und kann Ayhan Kublay nur weiterempfehlen!",
    stars: 5,
  },
  {
    id: 38,
    name: "Selin Gencer",
    text: "Hier wird saubere und gute Arbeit geleistet!Ayhan ist eine sehr liebenswerte und freundliche Frau. Bei ihr steht die Zufriedenheit der Kunden an erster Stelle.Ich hatte ein lash lifting.",
    stars: 5,
  },
  {
    id: 39,
    name: "Thomas Neugebauer",
    text: "Ayhan ist super nett, sehr kompetent man fühlt sich sehr wohl und gut aufgehoben bei Ihr. Ergebnis top, bin sehr zufrieden. Preis - Leistung einfach super. Jederzeit wieder, neuer Termin steht schon. LG Anita N. 👍💕",
    stars: 5,
  },
  {
    id: 40,
    name: "Hülya Öz",
    text: "Habe mir Wimpernlifting machen lassen bei Ayhan und bin mega zufrieden mit Ergebnis .Ayhan ist eine absolut freundliche und liebenswerte Person die ihr Fach wirklich versteht !!Danke für diese wunderschönen Wimpern ..😊liebe Ayhan ❤️Kann ich nur weiterempfehlen.",
    stars: 5,
  },
  {
    id:41 ,
    name: "Hanzi",
    text: "Ich habe eine Süße Frau kennengelernt, wer hat meine Lippen wunderschön tätowiert. Tolle Ergebnisse, perfekt Arbeit, mit voll liebe ♥️ sie ist einfach fantastisch!",
    stars: 5,
  },
  {
    id:42 ,
    name: "Esra Yanpinar",
    text: "Seit über 1 Jahr sind meine Wimpern perfekt… der Service, die Ambiente ist wunderbar…man fühlt sich während der Behandlung einfach nur wohl… kann ich jedem weiter empfehlen",
    stars: 5,
  },
  {
    id: 43,
    name: "Tina Stangl",
    text: "Sehr nett und zuvorkommend. Ich habe mich bei Ayhan sehr wohl gefühlt bin schon auf das Ergebnis gespannt. Einen tollen Pflegekit gab es auch noch dazu. Top!",
    stars: 5,
  },
  {
    id: 45,
    name: "Ceyda Pazar",
    text: "Sie ist einfach ein Herzensmensch😍 Ihre Arbeit eine 10/10!! Ich kann sie nur weiter empfehlen!! Schade, dass ich sie nicht noch früher kennengelernt habe. Einfach TOP!",
    stars: 5,
  },
  {
    id: 46,
    name: "ilka weiher",
    text: "Ich habe mich total wohl und gut aufgehoben gefühlt - das Ergebnis ust toll und ich werde auf jeden Fall wiederkommen - kann ich nur bestens weiterempfehlen! 🤩",
    stars: 5,
  },
  {
    id: 47,
    name: "M.P.",
    text: "Total herzlich. Total lieb ! Alles sehr sauber und gepflegt. Und ist sehr zuvorkommend. Danke für die „Extras“. 😊Freue mich auf den nächsten Termin.",
    stars: 5,
  },
  {
    id: 48,
    name: "Alexandra Knöpfle",
    text: "Ich habe mich sehr sehr wohl gefühlt und bin total glücklich mit dem ErgebnisLiebe Ayhan vielen Dank 🥰",
    stars: 5,
  },
  {
    id:49 ,
    name: "Julia Braun",
    text: "Ich bin super zufrieden und mega Glücklich. Sie hat sehr sauber und schön gearbeitet und ich überlege schon was ich als nächstes machen lasse",
    stars: 5,
  },
  {
    id:50 ,
    name: "Carmen Rommel",
    text: "Ich habe mir heute die Augenbrauen machen lassen. Einfach super gemacht 😃😘👍",
    stars: 5,
  },
  {
    id: 51,
    name: "Nadine Knoch",
    text: "Ayhan ist wirklich super sympathisch und nimmt sich viel Zeit. Ich kann Sie auf jeden Fall weiterempfehlen.",
    stars: 5
  },
  {
    id: 52,
    name: "Ecem Ardic",
    text: "War zum Augenbrauen und Wimpern Liften da super Leistung bin mega zufrieden und auch super lieb!",
    stars: 5,
  },
  {
    id: 53,
    name: "Emma Bucher",
    text: "Ich war total zufrieden und wurde super nett aufgenommen ! Immer wieder gern 🩷",
    stars: 5,
  },
  {
    id: 54,
    name: "A. Winter",
    text: "Ich bin jedes Mal seeeehr zufrieden mit deiner Arbeit, liebe Ayhan!🥰❤️",
    stars: 5,
  },
  {
    id: 55,
    name: "Natalie Dilmann",
    text: "Sehr netter Kontakt. Bin mit dem Ergebnis Powderbrowns sehr zufrieden. Danke Ayhan",
    stars: 5,
  },
  {
    id: 56,
    name: "Julia Glaß",
    text: "Super freundlich, schnelle Termine und Klasse Arbeit, komme auf jeden Fall wieder 😍",
    stars: 5,
  },
  {
    id: 57,
    name: "Claudia Almanstoetter",
    text: "Super nett ,gute Arbeit.Sehr gut aufgehoben gefühlt.",
    stars: 5,
  },
  {
    
  
  id: 58,
    name: "Maura Kummer",
    text: "Ich kann Ayhan gar nicht genug loben! Ihre Arbeit ist nicht nur hervorragend, sondern Sie ist super lieb und herzlich, geht auf Wünsche ein und hat viel Geduld.Ich bin begeistert von dem super natürlichen und zugleich akkuraten Ergebnis. Mann merkt einfach das ihr viel daran liegt das jeder zufrieden geht.Ich komme gerne wieder und ich empfehle die von Herzen.",
    stars: 5,
  },
  {
    id: 59,
    name: "Gabriele Schulz",
    text: "Super nett ,gute Arbeit.Sehr gut aufgehoben gefühlt.",
    stars: 5,
  },
  {
    id: 60,
    name: "Julia Roth",
    text: "Vielen Dank. Sehr kompetent. Immer wieder gerne.Ciao",
    stars: 5,
  },
  {
    id: 61,
    name: "Anna Almanstoetter",
    text: "Ich empfehle sie weiter.Sie macht eine saubere Arbeit.",
    stars: 5,
  },
  {
    id: 62,
    name: "ΝΑΝΑ ΓΕΩΡΓΙΑΔΟΥ",
    text: "sehr süße und freundliche Frau! sehr gute Arbeit!",
    stars: 5,
  },
  {
    id: 63,
    name: "Heike Kischkewitz",
    text: "",
    stars: 5,
  },
  {
    id: 64,
    name: "Anna Sourdis",
    text: "",
    stars: 5,
  },
  {
    id: 65,
    name: "Remzi Kublay",
    text: "",
    stars: 5,
  },
  {
    id: 66,
    name: "Mehtap Aksoy",
    text: "",
    stars: 5,
  },
 
];
