export const reviews = [
  {
    id: 1,
    name: "Iana Ibrahim",
    text: "All I can say is that Ayhan Kublay does a really beautiful and neat Eyelash-lifting. It is clear that the artist knows what she is doing and also her post on her instagram show her as a professional in this matter.",
    stars: 5,
  },
  {
    id: 2,
    name: "K.G.",
    text: "Einfach nur WOW! Ayhan hat mich sooooo freundlich und herzlich empfangen. Sie ist so ein herzlicher Mensch und sie berät einen einfach so toll. Ihre Arbeit ist einfach perfekt ! Leider gibt es nur 5 Sterne zu vergeben. Sie hat definitiv mehr verdient. Ich werde jetzt regelmäßig kommen und freue mich schon auf den nächsten Termin ♡",
    stars: 5,
  },
  {
    id: 3,
    name: "Mariam Hammoud",
    text: "bester Service aller Zeiten. Die Frau ist sehr freundlich und die Materialien sind so professionell. Sie hat die Arbeit korrigiert, die ich bei einer anderen Frau gemacht habe. Es war so professionell und detailbewusst. Die Ergebnisse sind perfekt, viel mehr als meine Erwartungen, und die Farbe ist so schön, echtes Braun. Die gesamte Linie meiner Wimpern wurde gezeichnet und mit einem Tattoo markiert, sodass meine Wimpern jetzt voller und dicker aussehen.",
    stars: 5,
  },
  {
    id: 4,
    name: "Maria Ziegler",
    text: "Ayhan arbeitet sehr präzise. Ihr ist es sehr wichtig, dass man mit dem Ergebnis zufrieden ist. Sie ist herzlich, ehrlich und hat sehr viel Geduld. Auf Wünsche werden eingegangen und die Beratung ist top! Ich kann Ayhan zu 110 % weiterempfehlen und bin mega zufrieden mit meinen Augenbrauen! Danke, danke, danke für diese tolle Arbeit!.",
    stars: 5,
  },
  {
    id:5,
    name: "YK",
    text: "Ich habe bei der lieben Ayhan eine Wimpernkranzverdichtung vornehmen lassen und bin mit dem Ergebnis sehr zufrieden. 🥰 Die Behandlung war schmerzfrei und das Ergebnis ist sehr schön. Ich werde oft darauf angesprochen und bin sehr glücklich damit.😊Ayhan war sehr zuvorkommend und hat sich viel Zeit für mich genommen. Wir haben spontan entschieden, meine Augenbrauen nachzustechen und sie hat das auch gleich gemacht.Ich bin sehr dankbar für die Empfehlung meiner Schwester und kann Ayhan nur weiterempfehlen.👍.",
    stars: 5,
  },
  {
    id: 6,
    name: "Meike Greiter",
    text: "Ayhan ist sehr freundlich und sehr erfahren. Man fühlt sich gut aufgehoben und ihre Arbeit ist einfach perfekt. Ich bin sehr zufrieden !.",
    stars: 5,
  },
  {
    id: 7,
    name: "Marion Karsch",
    text: "Von meiner Kosmetikerin haben mehrere Kunden die Ayhan empfohlen, weil sie sehr zufrieden waren. Ich hatte mir in der Türkei Oktober 2023 die Augenbrauen machen lassen und wegen notwendiger Nacharbeit suchte ich jemand in unserer Nähe. Vor dem ersten persönlichen Kontakt, habe ich Ayhan Bilder von meinen Augenbrauen gesendet. Da Ihr meine Augenbrauen nicht gefielen, wie mir selber auch nicht. Daraufhin hat sie mir einen persönlichen Beratungstermin angeboten. Mein Mann und ich sind gemeinsam zu ihr gefahren und waren sehr gut empfangen worden und eine Top Beratung erhalten. Zu diesem Zeitpunkt wollte sie mich nicht behandeln, weil es wirtschaftlich nichts gebracht hätte. Es soll die Zeit bis Herbst vergehen damit sie dann eine gute Arbeit ausführen kann. Von der ehrlichen Meinung von Ayhan waren wir sehr angenehm und positive überrascht. Nach einer Stunde sehr guten kostenloser Beratung, hat sie mir noch ein kleines Präsent und einen Pflegstift wegen Sonne für die Augenbrauen geschenkt.Ich freue mich schon auf den Herbsttermin bei Ayhan.",
    stars: 5,
  },
  {
    id: 8,
    name: "Sinem Kiran",
    text: "Absolut empfehlenswert! Bin immer wieder gerne bei ihr, sie macht sehr schöne Wimpernlifting 😍 Meine Wimpern halten bei ihr wirklich sehr sehr lang. Ich werde auch öfter darauf angesprochen, wo ich denn meine Wimpern machen lasse.Vielen Dank dafür! 🫶🏽.",
    stars: 5,
  },
  {
    id: 9,
    name: "Sabina Da Ma",
    text: "Ayhan ist eine super liebe. Sie ist sehr freundlich und nimmt sich Zeit für eine sehr gute Beratung und geht auf Kundenwünsche ein. Sehr zu empfehlen. Man fühlt sich direkt wohl bei ihr und in guten Händen. Weiter so!",
    stars: 5,
  },
  {
    id: 10,
    name: "Marins Müller",
    text: "Rundum perfekt 🥰Ayhan ist super lieb, nimmt sich Zeit, beratet toll und ehrlich und macht super Arbeit.Ich habe mich direkt wohl gefühlt und bin happy mit dem Ergebnis. Freue mich weitere Behandlung bei Ayhan machen zu lassen ☺️.",
    stars: 5,
  },
  {
    id: 11,
    name: "Ute Stein",
    text: "Ayhan hat mich sehr herzlich empfangen und mir die Behandlung eingehend erklärt. Nachdem sie mir einen Lidstrich tättowiert hat, werde ich auch für meine Augenbrauen zu ihr gehen. Ich freu mich schon.",
    stars: 5,
  },
  {
    id: 12,
    name: "B Fisher",
    text: "Ich habe mir eine Wimpernkranzverdichtung bei ihr stechen lassen, sieht total super aus und hat durch die Betäubungscreme nichtmal weh getan, nur ein bisschen gepiekst.Ayhan ist auch super lieb, hab mich gleich wohl gefühlt bei ihr! Die Terminvereinbarung erfolgt ganz unkompliziert über WhatsApp und wenn man Fragen hat oder irgendwas ist kann man sich jederzeit bei ihr melden.Kann sie nur empfehlen!Edit: Gehe immer wieder gerne zu ihr, habe mir jetzt noch ein Lippen PMU stechen lassen und das Ergebnis ist wirklich mega! 😍.",
    stars: 5,
  },
  {
    id:13 ,
    name: "Tina",
    text: "Ich habe mir von Ayhan Powderbrows stechen lassen, inkl. Korrektur der alten Arbeit aus einem großen Studio in Augsburg. Das Nachstechen steht noch aus, aber das Ergebnis ist schon jetzt sehr gut. Ich habe mich sehr gut aufgehoben gefühlt und wurde top beraten!",
    stars: 5,
  },
  {
    id:14 ,
    name: "Benjamin Gharbi",
    text: "Wer ein perfektes Permanent Ergebnis haben möchte, ist bei Ayhan genau richtig! Ich habe meinen Lidstrich und meine Augenbrauen auffrischen lassen.Und bin super begeistert!Saubere und gute Arbeit ist immer ihr Ziel! Ayhan ist sehr sympathisch und geht auf alle Wünsche ein. Ich bin sehr zufrieden und kann Sie nur jedem weiterempfehlen!",
    stars: 5,
  },
  {
    id:15 ,
    name: "Andrea Patzsch",
    text: "Ayhan ist eine sehr liebe Person und ich habe mich bei Ihr sehr wohl gefühlt. Sie hat meine Augenbrauen toll nach bearbeitet, nachdem ich in Augsburg bei jemand anderem schlechte Erfahrungen gemacht habe.",
    stars: 5,
  },
  {
    id:16 ,
    name: "Elmas Ozcelik",
    text: "Ayhan ist eine sehr liebe und ehlrliche Person. Ich wollte meine Lidstrich bei ihr machen lassen Sie hat mich so gut aufgklärt ich wusste sofort das ich in guten Händen bin einfach TOP...",
    stars: 5,
  },
  {
    id:17 ,
    name: "Jana Köln",
    text: "Ayhan ist ein so herzlicher Mensch und hat eine ganz liebevolle und lustige Art bei der man sich direkt wohlfühlt. Ihre Arbeit macht sie sehr sauber und einfach wunderschön. Bin sehr zufrieden bei ihr und werde definitiv wieder kommen",
    stars: 5,
  },
  {
    id:18 ,
    name: "Gülten Aytogmus",
    text: "Kompetente Beratung und super effektive Behandlung mit einem sofort sichtbaren Effekt! Sie nimmt sich sehr viel Zeit und gibt immer wertvolle Tipps mit. Ich freue mich auf jeden Termin bei ihr und kann das Studio herzlichst weiterempfehlen.Top",
    stars: 5,
  },
  {
    id:19 ,
    name: "Delina Patzsch",
    text: "Ayhan konnte meine Augenbrauen, welche von einem anderen Studio schlecht gemacht wurden, super korrigieren!!! Es sieht sehr viel besser aus als vorher.Zudem habe ich eine Top Beratung bekommen! Ich bin super zufrieden!",
    stars: 5,
  },
  {
    id:20 ,
    name: "Bettina P.",
    text: "Ich hatte heute meinen zweiten Termin für Powder Brows. Ich bin total happy, Ayhan als Beautyperle gefunden zu haben. Super sympathisch und ein tolles Ergebnis! Meine verzupften Naturbrauen, auch mit einer Vernarbung, waren bestimmt nicht der leichteste Fall. Ayhan arbeitet sehr korrekt und erklärt einem alles ganz toll! Die Betreuung während der Abheilphase war einzigartig.",
    stars: 5,
  },
  {
    id:21 ,
    name: "",
    text: ".",
    stars: 5,
  },
  {
    id:22 ,
    name: "",
    text: ".",
    stars: 5,
  },
];
